export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const myFont = localFont({ src: "./Shilla_Culture(M).otf", display: "swap" });
// const myFont2 = localFont({
//   src: "./yulyeo.ttf",
//   display: "swap",
// });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className="shilla">
      <body>{children}</body>
    </html>
  );
}
